image: microsoft/dotnet
stages:
  - build
  - pack
before_script:
  - 'dotnet restore -s "https://www.myget.org/F/avalonia-ci/api/v2" -s "https://api.nuget.org/v3/index.json"'
build:
  stage: build
  script:
    - 'dotnet build --no-restore'
  only:
    - master
    - develop

pack:
  stage: pack
  script:
    - './publish.sh'
  only:
    - master
    - develop
