image: microsoft/dotnet
stages:
  - build
before_script:
  - 'dotnet restore -s "https://www.myget.org/F/avalonia-ci/api/v2"'
build:
  stage: build
  script:
    - 'dotnet build --no-restore'
  only:
    - master
    - develop
