FROM mcr.microsoft.com/vscode/devcontainers/dotnet:0-6.0-focal

# [Optional] Uncomment this section to install additional OS packages.
RUN apt-get update --fix-missing && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install xz-utils zip nano
