//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace rec Andromeda.Core.FSharp

module InstalledGameLenses =
    open Andromeda.Core.FSharp

    let id =
        Lenses.Lens
            ((fun (x: InstalledGame) -> x.id),
             (fun (x: InstalledGame) (value: GogApi.DotNet.FSharp.DomainTypes.ProductId) -> { x with id = value }))

    let name =
        Lenses.Lens
            ((fun (x: InstalledGame) -> x.name), (fun (x: InstalledGame) (value: string) -> { x with name = value }))

    let path =
        Lenses.Lens
            ((fun (x: InstalledGame) -> x.path), (fun (x: InstalledGame) (value: string) -> { x with path = value }))

    let version =
        Lenses.Lens
            ((fun (x: InstalledGame) -> x.version),
             (fun (x: InstalledGame) (value: string) -> { x with version = value }))

    let updateable =
        Lenses.Lens
            ((fun (x: InstalledGame) -> x.updateable),
             (fun (x: InstalledGame) (value: bool) -> { x with updateable = value }))

    let icon =
        Lenses.Lens
            ((fun (x: InstalledGame) -> x.icon),
             (fun (x: InstalledGame) (value: string option) -> { x with icon = value }))
namespace rec Andromeda.Core.FSharp


namespace rec Andromeda.Core.FSharp

