name: Build

on: [push, pull_request]

jobs:
  build:
    name: Test building of Andromeda
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet: [5.0.100]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build Andromeda
      run: dotnet tool restore && dotnet paket restore && dotnet build
