name: Build

on: [push, pull_request]

jobs:
  build:
    name: Test building of Andromeda
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet: [3.1.402]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - uses: actions/cache@v2
      with:
        path: packages
        key: ${{ runner.OS }}-build-${{ hashFiles('**/paket.lock') }}
    - name: Build Andromeda
      run: dotnet tool restore && dotnet paket restore && dotnet fake build
