name: Build

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
    paths-ignore:
      - "**.md"
      - ".vscode/**"
      - ".devcontainer/**"
  pull_request:

jobs:
  build:
    name: Test building of Andromeda
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [6.0.101]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Build Andromeda
        run: dotnet run build
      - name: Run tests
        run: dotnet run test
