name: Deployment

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*"
    paths-ignore:
      - "**.md"
      - ".vscode/**"
      - ".devcontainer/**"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [6.0.101]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Restore
        run: dotnet tool restore && dotnet paket restore
      - name: Run publishing script
        run: dotnet run publish
      # For now I simply make a continuous build
      - name: Release files
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Continuous Build
          files: |
            LICENSE.txt
            deploy/*
