name: CI

on: push

jobs:
  build:
    name: Test building of Andromeda
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build Andromeda
      run: ./scripts/build.sh
