name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [3.1.302]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Restore tools
        run: dotnet tool restore && dotnet restore
      - name: Run Test
        run: dotnet fake build
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ github.ref }}
          path: ./CHANGELOG.md
      - name: Run publishing script
        run: ./scripts/publish.sh ${{ github.ref }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog_reader.outputs.log_entry }}
          draft: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
          prerelease: false
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deploy/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
