name: Visualize

on: workflow_dispatch

jobs:
  visualize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: "images/diagram.svg"
          excluded_paths: "dist,node_modules"
